server:
  port: 8000

spring:
  application:
    name: ms-users
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8080/realms/cognito-hub}
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5432/cognito
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: "/"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


keycloak:
  auth-server-url: http://localhost:8080
  autodetect-bearer-only: true
  credentials:
    secret: xLnnPpvGRBkekbUuVLnnudrkSVDTCzFc
    realm: cognito-hub
    resource: backend

management:
  tracing:
    sampling:
      probability: 1.0


token:
  converter:
    principal-attribute: preferred_username
    resource-id: cognito-hub
security:
  routes:
    - path: /api/v1/users/students
      method: POST
      roles: []
    - path: /api/v1/users/professors
      method: POST
      roles: []
    - path: /api/v1/users/professors/**
      method: GET
      roles: [CREATE-COURSES]
    - path: /api/v1/users/students/{userId}/subscription
      method: GET
      roles: [VIEW-COURSES]


