server:
  port: 8000

spring:
  application:
    name: ms-users
  datasource:
    url: jdbc:postgresql://localhost:5432/cognito-hub
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: "/"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


keycloak:
  auth-server-url: http://localhost:8080
  autodetect-bearer-only: true
  credentials:
    secret: xLnnPpvGRBkekbUuVLnnudrkSVDTCzFc
    realm: cognito-hub
    resource: backend

management:
  tracing:
    sampling:
      probability: 1.0





