POST http://localhost:8000/api/v1/users/card
Content-Type: application/json

{
    "bankName": "Bisa",
    "number": "1234567890",
    "expiration": "2026-12-31",
    "titular": "Pedro Perez",
    "cvv": "123",
    "userKeycloakId": "23772082-fe41-4dcc-9d10-e4a127447c9e"
}
###
GET http://localhost:8000/api/v1/users/23772082-fe41-4dcc-9d10-e4a127447c9e/card