POST http://localhost:8000/api/v1/users/card
Content-Type: application/json

{
    "bankName": "BNB",
    "number": "1234567890",
    "expiration": "2026-12-31",
    "titular": "Ale flores",
    "cvv": "123",
    "userKeycloakId": "be62fdee-5a5d-4a41-ade2-9a182faedb47"
}
###
GET http://localhost:8000/api/v1/users/be62fdee-5a5d-4a41-ade2-9a182faedb47/card
###
PUT http://localhost:8000/api/v1/users/card/4
