POST http://localhost:8000/api/v1/users/professors/course
Content-Type: application/json

{
  "title": "Curso Arquitectura",
  "description": "Descripción del curso",
  "amount": 99.99,
  "version": 1,
  "duration": 30,
  "languageId": 1,
  "levelId": 2,
  "subCategoryId": 3,
  "professorKeycloakId": "b1b22ac1-f533-4050-8f75-9c28f07843f3"
}


###
GET http://localhost:8000/api/v1/users/professors/d4ab900f-3fe0-44ba-aacd-4ad74a7738ce/courses