POST http://localhost:8000/api/v1/users/professors/course
Content-Type: application/json

{
  "title": "Curso de Ejemplo 2",
  "description": "Descripción del curso",
  "amount": 99.99,
  "version": 1,
  "duration": 30,
  "languageId": 1,
  "levelId": 2,
  "subCategoryId": 3,
  "professorKeycloakId": "56b79765-583b-4a42-8b05-c2d67fb11869"
}


###
GET http://localhost:8000/api/v1/users/professors/d4ab900f-3fe0-44ba-aacd-4ad74a7738ce/courses