POST http://localhost:8000/api/v1/users/professors/course
Content-Type: application/json

{
  "title": "Curso de Ejemplo",
  "description": "Descripción del curso",
  "amount": 99.99,
  "version": 1,
  "duration": 30,
  "languageId": 1,
  "levelId": 2,
  "subCategoryId": 3,
  "professorKeycloakId": "d4ab900f-3fe0-44ba-aacd-4ad74a7738ce"
}


###