POST http://localhost:8000/api/v1/users/students
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "username": "Alejandroxd",
  "email": "Alexd@gmail.com",
  "firstName": "alexd",
  "lastName": "floresxd",
  "password": "1234"
}
###
GET http://localhost:8000/api/v1/users/ffa27ed2-5096-4876-b299-b5a2e69c87a1

###
POST http://localhost:8000/api/v1/users/professors
Content-Type: application/json

{
  "username": "sebas",
  "email": "sebas@gmail.com",
  "firstName": "ale",
  "lastName": "flores",
  "password": "1234"
}

###

GET http://localhost:8000/api/v1/users/professors/2